name: out_of_context
description: Out of Context provides context-free navigation & scaffolds in Flutter.
version: 2.0.0
homepage: https://github.com/forus-labs/cauldron
repository: https://github.com/forus-labs/cauldron

environment:
  flutter: '>=2.2.2'
  sdk: '>=2.13.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8

dev_dependencies:
  build_runner: ^2.0.5
  flint: ^2.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.10