name: out_of_context
description: Context-free navigation, scaffolds & snackbars in Flutter
version: 1.0.5
homepage: https://github.com/forus-labs/cauldron
repository: https://github.com/forus-labs/cauldron

environment:
  sdk: '>=2.8.4 <3.0.0'

dependencies:
  meta: ^1.1.8
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.14.7
  mockito: ^4.1.1