name: out_of_context
description: Out of Context provides context-free navigation & scaffolds in Flutter.
version: 1.1.0+1
homepage: https://github.com/forus-labs/cauldron
repository: https://github.com/forus-labs/cauldron

environment:
  flutter: '>=1.22.0 <2.0.0'
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flint: ^1.3.1
  mockito: ^4.1.1