language: dart
sudo: false
dist: bionic

dart:
  - stable

jobs:
  include:
    - stage: "Test"
      name: "Flint"
      before_script:
        - cd $TRAVIS_BUILD_DIR/flint/
        - pub get
      script:
        - dartanalyzer lib auto_updater --fatal-warnings


after_success:
  - bash <(curl -s https://codecov.io/bash)