language: dart
sudo: false
dist: bionic

dart:
  - stable

jobs:
  include:
    - stage: "Test"
      name: "Flint"
      before_script:
        - cd $TRAVIS_BUILD_DIR/flint/
      script:
        - dartanalyzer lib --fatal-warnings auto_updater


after_success:
  - bash <(curl -s https://codecov.io/bash)