language: dart
sudo: false
dist: bionic

dart:
  - stable

cache:
  directories:
    - $HOME/.pub-cache

stages:
  - "Test"
  - "Reports"

jobs:
  include:
    - stage: "Test"
      name: "Flint"
      before_script:
        - cd $TRAVIS_BUILD_DIR/flint/
        - pub get
      script:
        - dartanalyzer lib auto_updater --fatal-warnings

    - stage: "Test"
      name: "Out of Context"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - lib32stdc++6
            - fonts-noto
      install: true
      before_script:
        - cd $TRAVIS_BUILD_DIR/out_of_context/
        - git clone https://github.com/flutter/flutter.git -b stable --depth 1

      script:
        - ./flutter/bin/flutter test --coverage

    - stage: "Reports"
      name: "Codecov"
      after_success:
        - bash <(curl -s https://codecov.io/bash)