language: dart
dist: focal

dart:
  - stable

cache:
  directories:
    - $HOME/.pub-cache

jobs:
  include:
    - stage: "Test"
      name: "Flint"
      before_script:
        - cd $TRAVIS_BUILD_DIR/flint/
        - pub get
        
      script:
        - dartanalyzer lib auto_updater --fatal-warnings

    - stage: "Test"
      name: "Out of Context & Mock of Context"
      before_script:
        - cd $TRAVIS_BUILD_DIR/../
        - git clone https://github.com/flutter/flutter.git -b stable --depth 1
        - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH

      script:
        - cd $TRAVIS_BUILD_DIR/out_of_context/
        - flutter analyze
        - flutter test --coverage

        - cd $TRAVIS_BUILD_DIR/mock_of_context/
        - flutter analyze
        - flutter test --coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)