coverage:
  status:
    project:
      default:
        flags: [off]
      flint:
        flags: [flint]
      sugar:
        flags: [sugar]

ignore:
  - "**/flutter-tools"
  - "**/*.g.dart"

flags:
  # filter the folder(s) you wish to measure by that flag
  flint:
    paths:
      - flint/lib/
  sugar:
    paths:
      - sugar/lib/