name: flint
description: Forus Labs' sets of dartanalyzer lints that we use internally in our Dart & Flutter projects.
version: 2.1.2
homepage: https://github.com/forus-labs/cauldron
repository: https://github.com/forus-labs/cauldron

environment:
  sdk: '>=2.14.0 <3.0.0'

dev_dependencies:
  html: ^0.15.0
  http: ^0.13.3
  yaml: ^3.1.0
