name: flint
description: Forus Labs' sets of dartanalyzer lints that we use internally in our Dart & Flutter projects.
version: 1.3.0
homepage: https://github.com/forus-labs/cauldron
repository: https://github.com/forus-labs/cauldron

environment:
  sdk: '>=2.10.0 <3.0.0'

dev_dependencies:
  yaml: ^2.2.1
