name: nitrogen_types
description: Companion library for Nitrogen.

version: 0.1.0
homepage: https://github.com/forus-labs/cauldron/nitrogen

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flint: ^2.7.0
