name: nitrogen_types
description: Companion library for Nitrogen. Provides shared types that generated bindings use.

version: 0.3.0
homepage: https://github.com/forus-labs/cauldron/tree/master/nitrogen
repository: https://github.com/forus-labs/cauldron/

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flint: ^2.7.0
