name: mock_of_context
description: Mock of Context is a companion project for testing Out of Context.
version: 2.0.0
homepage: https://github.com/forus-labs/cauldron
repository: https://github.com/forus-labs/cauldron

environment:
  flutter: '>=2.2.2'
  sdk: '>=2.13.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8
  mockito: ^5.0.10
  out_of_context: ^2.0.0

dev_dependencies:
  build_runner: ^2.0.5
  flutter_test:
    sdk: flutter
  flint: ^2.0.0