name: jeeves
description: Jeeves is a command-line tool that simplifies environment management
version: 1.0.0
homepage: https://github.com/forus-labs/cauldron
repository: https://github.com/forus-labs/cauldron

environment:
  sdk: '>=2.14.1 <3.0.0'

dependencies:
  args: ^2.3.0
  yaml: ^3.1.0

dev_dependencies:
  flint: ^2.1.0
  test: ^1.17.9
