name: jeeves
description: Jeeves is a command-line tool that simplifies flutter development
version: 1.0.0
homepage: https://github.com/forus-labs/cauldron
repository: https://github.com/forus-labs/cauldron

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  ansicolor: ^2.0.1
  args: ^2.3.0
  yaml: ^3.1.0

dev_dependencies:
  flint: ^2.2.0
  test: ^1.17.9
