builders:
  lingua_generator:
    import: "package:lingua/lingua.dart"
    builder_factories: ["build"]
    build_extensions:
      .dart:
        - lingua.g.dart
    build_to: "cache"
    auto_apply: root_package

