name: lingua
description: Forus Labs' internationlization library for Flutter
version: 0.0.1
author: Forus Labs
homepage: https://github.com/forus-labs/cauldron
repository: https://github.com/forus-labs/cauldron

environment:
  sdk: ">=2.8.4 <3.0.0"

dependencies:
  build: ^1.3.0
  flutter:
    sdk: flutter
  glob: ^1.2.0
  meta: ^1.1.8
  source_gen: ^ 0.9.5
  yaml: ^2.2.1

dev_dependencies:
  build_runner: ^1.10.0
  flutter_test:
    sdk: flutter
  flint: ^1.0.7
  mockito: ^4.1.1
