name: sugar
description: Forus Labs' extended standard library. Provide syntax sugar for working with collections, date-times, monads & timezones.
version: 3.0.0
homepage: https://github.com/forus-labs/cauldron
repository: https://github.com/forus-labs/cauldron
issue_tracker: https://github.com/forus-labs/cauldron/issues
documentation: https://pub.dev/documentation/sugar/latest/

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  ffi: ^2.0.1
  js: ^0.6.7
  meta: ^1.8.0

dev_dependencies:
  flint: ^2.6.0
  http: ^0.13.5
  path: ^1.8.3
  test: ^1.17.9
  timezone: ^0.9.1
