name: sugar
description: Forus Labs' Core Dart library. Provides sweet syntax sugar for common patterns related to the collections, core sand time.
version: 3.0.0
homepage: https://github.com/forus-labs/cauldron
repository: https://github.com/forus-labs/cauldron

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  meta: ^1.8.0

dev_dependencies:
  flint: ^2.6.0
  test: ^1.17.9