name: sugar
description: Forus Labs' standard library extension. Utilities for date-times, timezones, collections, monads & more.

version: 3.0.0
homepage: https://github.com/forus-labs/cauldron
repository: https://github.com/forus-labs/cauldron
issue_tracker: https://github.com/forus-labs/cauldron/issues
documentation: https://pub.dev/documentation/sugar/latest/

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  ffi: ^2.0.1
  js: ^0.6.7
  meta: ^1.8.0

dev_dependencies:
  coverage: ^1.6.3
  flint: ^2.7.0
  http: ^0.13.5
  path: ^1.8.3
  test: ^1.17.9
  timezone: ^0.9.1
