name: sugar
description: Forus Labs' Core Dart library.
version: 1.0.0
homepage: https://github.com/forus-labs/cauldron/sugar
repository: https://github.com/forus-labs/cauldron/sugar

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  meta: ^1.1.7

dev_dependencies:
  flint: ^1.1.1
  test: ^1.9.4
  test_coverage: ^0.4.0
  mockito: ^4.1.1
