include: package:flint/analysis_options.flutter.yaml
linter:
  rules:
    - avoid_renaming_method_parameters
    - use_build_context_synchronously
analyzer:
  errors:
    deprecated_member_use: ignore # TODO: enable once they fix the WillPopScope nonsense
    diagnostic_describe_all_properties: ignore
    unused_result: ignore # The rule seems to break almost every release.
    use_build_context_synchronously: ignore
