name: mock_of_context_example
description: Example for mock_of_context
private: true
version: 1.0.0
homepage: https://github.com/forus-labs/cauldron
repository: https://github.com/forus-labs/cauldron

environment:
  flutter: '>=2.2.2'
  sdk: '>=2.13.3 <3.0.0'