name: mock_of_context_example
description: Example for mock_of_context
private: true
version: 1.0.0
homepage: https://github.com/forus-labs/cauldron
repository: https://github.com/forus-labs/cauldron

environment:
  flutter: '>=1.22.0 <2.0.0'
  sdk: '>=2.10.0 <3.0.0'