# Configuration for build runners. See https://github.com/dart-lang/build/blob/master/build_config/README.md

targets:
  $default:
    sources:
      - assets/**
      - lib/$lib$
      - pubspec.*
      - $package$

builders:
  nitrogen_flutter_svg:
    import: "package:nitrogen_lottie/nitrogen_lottie.dart"
    builder_factories: [ "nitrogenLottieBuilder" ]
    build_extensions: { "$package$": [ "lib/src/lottie_extension.nitrogen.dart" ] }
    auto_apply: dependents
    build_to: source
