name: nitrogen_lottie
description: lottie extension for Nitrogen.

version: 0.1.0
homepage: https://github.com/forus-labs/cauldron/nitrogen

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  build: ^2.4.1
  build_runner: ^2.4.6
  code_builder: ^4.10.0
  flutter:
    sdk: flutter
  # We depend on flutter_svg so that users installing this extension will get a version compatible with the flutter_svg
  # version that they're using.
  lottie: ^3.1.0
  nitrogen:
    path:
      ../nitrogen
  path: ^1.9.0

dev_dependencies:
  flint: ^2.7.0
