include: package:flint/analysis_options.flutter.yaml
analyzer:
  exclude:
    - lib/**.*.dart
    - test/**.*.dart
  errors:
    sort_unnamed_constructors_first: ignore
    unused_result: ignore

linter:
  rules:
    avoid_print: ignore

