# Configuration for build runners. See https://github.com/dart-lang/build/blob/master/build_config/README.md

targets:
  $default:
    builders:
      stevia_runner:
        enabled: true

builders:
  steviaAssetGenerator:
    import: "package:stevia_runner/stevia_asset_generator.dart"
    builder_factories: [ "build" ]
    build_extensions: { "$lib$": [ ".gen.dart" ] }
    auto_apply: dependents
    build_to: source