name: stevia_runner
description: A build_runner for Stevia.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
 build: ^2.4.0
 code_builder: ^4.5.0
 dart_style: ^2.3.0
 io: ^1.0.3
 path: ^1.8.0
 sugar: ^3.1.0
 yaml: ^3.1.0

dev_dependencies:
  flint: ^2.7.0
  test: ^1.24.0

import_sorter:
 comments: false