name: Nitrogen Unit Tests
on:
  push:
    paths:
      - nitrogen/**
      - nitrogen_flutter_svg/**
      - nitrogen_lottie/**
      - nitrogen_types/**
      - .github/workflows/nitrogen.yaml

  pull_request:
    paths:
      - nitrogen/**
      - nitrogen_flutter_svg/**
      - nitrogen_lottie/**
      - nitrogen_types/**
      - .github/workflows/nitrogen.yaml

jobs:
  test-nitrogen:
    name: Run nitrogen tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: nitrogen
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - run: dart analyze --fatal-warnings
      - run: dart run coverage:test_with_coverage
      - run: sudo apt-get update -y
      - run: sudo apt-get install -y lcov
      - run: lcov --remove ./coverage/lcov.info '**.g.dart' -o ./coverage/lcov.info
      - uses: codecov/codecov-action@v4
        with:
          files: ./nitrogen/coverage/lcov.info

  test-nitrogen-flutter-svg:
    name: Run nitrogen_flutter_svg tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: nitrogen_flutter_svg
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2.16.0
      - run: flutter pub get
      - run: flutter analyze

  test-nitrogen-lottie:
    name: Run nitrogen_lottie tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: nitrogen_lottie
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2.16.0
      - run: flutter pub get
      - run: flutter analyze

  test-nitrogen-types:
    name: Run nitrogen_types tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: nitrogen_types
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - run: dart analyze --fatal-warnings
