name: Out of Context Build

on:
  push:
    paths: [ out_of_context/**, .github/workflows/out_of_context.yml ]
    branches: [ master, staging, stable, fix/**, feature/** ]
    
  pull_request:
    paths: [ out_of_context/**, .github/workflows/out_of_context.yml ]
    branches: [ master, staging, stable ]

jobs:
  tests:
    name: Automated tests
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: out_of_context

    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1.3.2
    - run: flutter analyze
    - run: flutter test --coverage
    - uses: axel-op/dart-package-analyzer@v2
      with:
        relativePath: out_of_context
        githubToken: ${{ secrets.GITHUB_TOKEN }}
    - run: bash <(curl -s https://codecov.io/bash)
