name: Sugar

on:
  push:
    paths: [ sugar/**, .github/workflows/sugar.yaml ]

  pull_request:
    paths: [ sugar/**, .github/workflows/sugar.yaml ]

jobs:
  test:
    name: Run agnostic tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sugar

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - run: dart analyze --fatal-warnings
      - run: dart run coverage:test_with_coverage
      - uses: codecov/codecov-action@v3
        with:
          files: ./sugar/coverage/lcov.info

  test-windows:
    name: Run platform-dependent tests on Windows
    needs: [ test ]
    runs-on: windows-latest
    defaults:
      run:
        working-directory: sugar
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - run: dart test -t "platform-specific"

  test-posix:
    name: Run platform-dependent tests on POSIX platforms
    needs: [ test ]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]
    defaults:
      run:
        working-directory: sugar
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - run: dart test -t "platform-specific"

  test-web:
    name: Run platform-dependent tests on web platforms
    needs: [ test ]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sugar
    steps:
      - uses: actions/checkout@v3

      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: latest

      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - run: dart test -t "platform-specific" -p "chrome"
      - run: dart test -t "platform-specific" -p "firefox"