name: Sugar Build

on:
  push:
    paths: [ sugar/**, .github/workflows/sugar.yml ]
    branches: [ master, staging, stable, fix/**, feature/** ]

  pull_request:
    paths: [ sugar/**, .github/workflows/sugar.yml ]
    branches: [ master, staging, stable ]

jobs:
  tests:
    name: Automated tests
    runs-on: ubuntu-20.04
    container:
      image: google/dart:latest
    defaults:
      run:
        working-directory: sugar

    steps:
      - uses: actions/checkout@v2
      - run: pub get
      - run: dart analyze --fatal-warnings lib
      - uses: axel-op/dart-package-analyzer@v3
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          relativePath: sugar
      - run: dart test --platform vm --coverage=./coverage/raw
      - run: pub global activate coverage
      - run: pub global run coverage:format_coverage --packages=.packages -l -i ./coverage/raw -o ./coverage/lcov.info --report-on=lib
      - run: apt-get update -y
      - run: apt-get install -y lcov
      - run: lcov --remove ./coverage/lcov.info 'lib/**.g.dart' -o ./coverage/lcov.info
      - uses: codecov/codecov-action@v1
        with:
          relativePath: sugar
          files: ./coverage/lcov.info
          fail_ci_if_error: true