name: Sugar Integration Tests

on:
  push:
    paths:
      - .github/workflows/sugar_integration_test.yaml
      - sugar/integration_test/**
      - sugar/lib/**
      - sugar/tool/**
      - sugar/dart_test.yaml
      - sugar/pubspec.yaml

  pull_request:
    paths:
      - .github/workflows/sugar_integration_test.yaml
      - sugar/integration_test/**
      - sugar/lib/**
      - sugar/tool/**
      - sugar/dart_test.yaml
      - sugar/pubspec.yaml

jobs:
  windows:
    name: Run integration tests on Windows
    runs-on: windows-latest
    defaults:
      run:
        working-directory: sugar
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - run: dart run coverage:test_with_coverage test ./integration_test/
      - uses: codecov/codecov-action@v3
        with:
          files: ./sugar/coverage/lcov.info

  macos:
    name: Run integration tests on macOS
    runs-on: macos-latest
    defaults:
      run:
        working-directory: sugar
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - run: chmod +x ./integration_test/src/time/zone/platform/platform_provider_test_macos.sh
      - run: ./integration_test/src/time/zone/platform/platform_provider_test_macos.sh
      - uses: codecov/codecov-action@v3
        with:
          files: ./sugar/coverage/lcov.info

  linux:
    name: Run integration tests on linux
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sugar
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - run: chmod +x ./integration_test/src/time/zone/platform/platform_provider_test_linux.sh
      - run: ./integration_test/src/time/zone/platform/platform_provider_test_linux.sh
      - uses: codecov/codecov-action@v3
        with:
          files: ./sugar/coverage/lcov.info

  web:
    name: Run integration tests on web
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sugar
    steps:
      - uses: actions/checkout@v3
      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
      - uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: latest
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - run: chmod +x ./integration_test/src/time/zone/platform/platform_provider_test_browser.sh
      - run: ./integration_test/src/time/zone/platform/platform_provider_test_browser.sh
      - uses: codecov/codecov-action@v3
        with:
          files: ./sugar/coverage/lcov.info