name: Sugar Build

on:
  push:
    paths: [ sugar/**, .github/workflows/sugar.yml ]
    branches: [ master, staging, stable, fix/**, feature/** ]

  pull_request:
    paths: [ sugar/**, .github/workflows/sugar.yml ]
    branches: [ master, staging, stable ]

jobs:
  tests:
    name: Automated tests
    runs-on: ubuntu-20.04
    container:
      image: google/dart:latest
    defaults:
      run:
        working-directory: sugar

    steps:
      - uses: actions/checkout@v2
      - run: pub get
      - run: dart analyze --fatal-warnings lib
      - run: pub test test --platform vm
      - run: pub run test_coverage
      - uses: axel-op/dart-package-analyzer@v3
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          relativePath: sugar
      - uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true